Parameters:
  lambdaFunctionName:
    Type: String
    Default: my-lambda-function

Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          def handler(event, context):
            return {
              'body' : 'Hello World from Lambda!',
              'statusCode' : 200
            }
      FunctionName: !Ref lambdaFunctionName
      Description: Hello world lambda function
      Handler: index.handler
      Role: !GetAtt IAMRole.Arm
      Runtime: python3.9

  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      Path: /
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"
          PolicyName: lambda
